# Generated by Django 4.2.1 on 2023-06-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', 'procedure_and_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
